import { GeistMono, GeistSans } from "geist/font";
import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ar" dir="rtl">
			<body
				className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
			>
				<LanguageProvider>
					{children}
				</LanguageProvider>
			</body>
		</html>
	);
}
